spin_manifest_version = 2

[application]
name = "caincun-travel"
version = "0.1.0"
authors = ["The Team Where Half of its Members Have Names Starting with 'M'"]
description = "a travel agency website with a twist"

[[trigger.http]]
route = "/cooke-router/"
component = "cookie-router"

[component.cookie-router]
source = "cookie-router/target/wasm32-wasip1/release/cookie_router.wasm"
key_value_stores = ["default"]
# self not allowed in FWF (?)
# allowed_outbound_hosts = ["http://self"]
allowed_outbound_hosts = ["*://*:*"]
[component.cookie-router.build]
command = "cd cookie-router && cargo build --target wasm32-wasip1 --release"
watch = ["cookie-router/src/**/*.rs", "cookie-router/Cargo.toml"]

[[trigger.http]]
route = "/..."
component = "site"

# TODO: site broken; what paths do we need to change so that /css and /image, etc are under /site?

[component.site]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.3.0/spin_static_fs.wasm", digest = "sha256:ef88708817e107bf49985c7cefe4dd1f199bf26f6727819183d5c996baa3d148" }
files = [{ source = "ui/app", destination = "/" }]
# Is a bug in the fileserver, also PR default spin icon ad favicon
environment = { FALLBACK_PATH = "index.html" }

[[trigger.http]]
route = "/api/..."
component = "engine"

[component.engine]
source = "engine/dist/engine.wasm"
exclude_files = ["engine/**/node_modules"]
[component.engine.build]
command = ["npm install", "npm run build"]
workdir = "engine"
watch = ["src/**/*.ts"]
