spin_manifest_version = 2

[application]
authors = ["Mikkel Mørk Hegnhøj <mikkel@fermyon.com>"]
description = ""
name = "engine"
version = "0.1.0"

[[trigger.http]]
route = "/api/..."
component = "engine"

[component.engine]
source = "dist/engine.wasm"
exclude_files = ["**/node_modules"]
[component.engine.build]
command = ["npm install", "npm run build"]
watch = ["src/**/*.ts"]

[[trigger.http]]
route = "/..."
component = "fileserver"

[component.fileserver]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.3.0/spin_static_fs.wasm", digest = "sha256:ef88708817e107bf49985c7cefe4dd1f199bf26f6727819183d5c996baa3d148" }
files = [{ source = "assets", destination = "/" }]
[component.fileserver.build]
command = [""]
watch = ["assets/*.*"]