spin_manifest_version = 2

[application]
authors = ["Mikkel Mørk Hegnhøj <mikkel@fermyon.com>"]
description = ""
name = "engine"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "engine"

[component.engine]
source = "dist/engine.wasm"
exclude_files = ["**/node_modules"]
[component.engine.build]
command = ["npm install", "npm run build"]
watch = ["src/**/*.ts"]